openapi: 3.0.3
info:
  title: Auth API
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /auth/login:
    post:
      summary: Autenticar e obter JWT
      tags:
        - Autenticação
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Token retornado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Credenciais inválidas

  /api/hello:
    get:
      summary: Testar autenticação JWT
      description: Retorna uma saudação se o token JWT for válido.
      tags:
        - Teste Autenticado
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Sucesso – token válido
          content:
            application/json:
              schema:
                type: string
                example: "Olá! Você está autenticado."
        '401':
          description: Token ausente ou inválido

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LoginRequest:
      type: object
      properties:
        username:
          type: string
          example: admin
        senha:
          type: string
          example: 123456
      required:
        - username
        - senha

    LoginResponse:
      type: object
      properties:
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

security:
  - bearerAuth: []
